"use client";
import { apiFetch } from "@/lib/api";
import { Check, Cloud, LoaderCircle, Mail, Save } from "lucide-react";
import { useEffect, useState } from "react";
import styles from "./contact-settings.module.css";
type Settings = { recipientEmail?: string; turnstileEnabled: boolean; turnstileSiteKey?: string; turnstileSecretConfigured: boolean };
export function ContactSettings() {
 const [data,setData]=useState<Settings>(); const [secret,setSecret]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{apiFetch<Settings>("/admin/contact-settings").then(setData).catch((e:Error)=>setMessage(e.message));},[]);
 async function save(){if(!data)return;setSaving(true);setMessage("");try{const updated=await apiFetch<Settings>("/admin/contact-settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientEmail:data.recipientEmail,turnstileEnabled:data.turnstileEnabled,turnstileSiteKey:data.turnstileSiteKey,...(secret?{turnstileSecretKey:secret}:{})})});setData(updated);setSecret("");setMessage("Configuración de contacto guardada.");}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar.");}finally{setSaving(false)}}
 if(!data)return <div className={styles.loading}><LoaderCircle/>Cargando configuración…</div>;
 return <main className={styles.page}><header><div><span>Configuración · Contacto</span><h1>Contacto y protección anti-spam</h1><p>Define quién recibe los formularios y protege los envíos con Cloudflare Turnstile.</p></div><button onClick={()=>void save()} disabled={saving}>{saving?<LoaderCircle className={styles.spin}/>:<Save/>}Guardar</button></header><section><div className={styles.title}><Mail/><div><h2>Recepción de solicitudes</h2><p>Las solicitudes siempre se almacenan en el panel, incluso si el correo falla.</p></div></div><label>Correo destinatario<input type="email" value={data.recipientEmail||""} onChange={e=>setData({...data,recipientEmail:e.target.value})} placeholder="contacto@tu-dominio.com"/></label></section><section><div className={styles.title}><Cloud/><div><h2>Cloudflare Turnstile</h2><p>Captcha respetuoso con la privacidad administrado desde tu cuenta de Cloudflare.</p></div></div><label className={styles.check}><input type="checkbox" checked={data.turnstileEnabled} onChange={e=>setData({...data,turnstileEnabled:e.target.checked})}/>Activar Turnstile en el formulario público</label><div className={styles.grid}><label>Site key<input value={data.turnstileSiteKey||""} onChange={e=>setData({...data,turnstileSiteKey:e.target.value})} placeholder="0x4AAAA..."/></label><label>Secret key<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={data.turnstileSecretConfigured?"Configurada · escribe para reemplazar":"Ingresa la clave secreta"}/></label></div>{data.turnstileSecretConfigured&&<small className={styles.configured}><Check/>Clave secreta cifrada y configurada</small>}</section>{message&&<p className={styles.message}>{message}</p>}</main>;
}
