"use client";
import { StudentNavbar } from "@/components/student-navbar/student-navbar";
import { apiFetch } from "@/lib/api";
import { LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import styles from "./account.module.css";
type Profile={phone?:string;whatsapp?:string;birthDate?:string;country?:string;state?:string;city?:string;postalCode?:string;company?:string;jobTitle?:string;bio?:string};
type User={email:string;firstName:string;lastName:string;profile?:Profile|null};
const blank:Profile={phone:"",whatsapp:"",birthDate:"",country:"México",state:"",city:"",postalCode:"",company:"",jobTitle:"",bio:""};
export function ProfileForm(){
 const [user,setUser]=useState<User|null>(null);const [profile,setProfile]=useState<Profile>(blank);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const router=useRouter();
 useEffect(()=>{void apiFetch<User>("/auth/me").then((value)=>{setUser(value);setProfile({...blank,...value.profile,birthDate:value.profile?.birthDate?.slice(0,10)||""});}).catch(()=>router.replace("/login?next=/mi-cuenta"));},[router]);
 function field(key:keyof Profile,value:string){setProfile((current)=>({...current,[key]:value}));}
 async function save(){if(!user)return;setSaving(true);setMessage("");try{const updated=await apiFetch<User>("/auth/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:user.firstName,lastName:user.lastName,...profile,birthDate:profile.birthDate||undefined})});setUser(updated);setMessage("Información actualizada correctamente.");}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar");}finally{setSaving(false)}}
 if(!user)return <main className={styles.loading}><LoaderCircle/></main>;
 const initials=`${user.firstName[0]}${user.lastName[0]}`.toUpperCase();
 return <main className={styles.page}><StudentNavbar/><div className={styles.shell}><header className={styles.header}><span className={styles.avatar}>{initials}</span><div><h1>Mi cuenta</h1><p>Completa tu información personal, profesional y de contacto.</p></div></header><section className={styles.card}><h2>Datos personales</h2><div className={styles.grid}><label>Nombre<input value={user.firstName} onChange={(e)=>setUser({...user,firstName:e.target.value})}/></label><label>Apellidos<input value={user.lastName} onChange={(e)=>setUser({...user,lastName:e.target.value})}/></label><label>Correo electrónico<input value={user.email} disabled/></label><label>Fecha de nacimiento<input type="date" value={profile.birthDate||""} onChange={(e)=>field("birthDate",e.target.value)}/></label><label>Teléfono<input value={profile.phone||""} onChange={(e)=>field("phone",e.target.value)} placeholder="+52…"/></label><label>WhatsApp<input value={profile.whatsapp||""} onChange={(e)=>field("whatsapp",e.target.value)} placeholder="+52…"/></label></div><h2>Ubicación</h2><div className={styles.grid}><label>País<input value={profile.country||""} onChange={(e)=>field("country",e.target.value)}/></label><label>Estado<input value={profile.state||""} onChange={(e)=>field("state",e.target.value)}/></label><label>Ciudad<input value={profile.city||""} onChange={(e)=>field("city",e.target.value)}/></label><label>Código postal<input value={profile.postalCode||""} onChange={(e)=>field("postalCode",e.target.value)}/></label></div><h2>Perfil profesional</h2><div className={styles.grid}><label>Empresa<input value={profile.company||""} onChange={(e)=>field("company",e.target.value)}/></label><label>Puesto o profesión<input value={profile.jobTitle||""} onChange={(e)=>field("jobTitle",e.target.value)}/></label><label className={styles.full}>Acerca de ti<textarea maxLength={1000} value={profile.bio||""} onChange={(e)=>field("bio",e.target.value)} placeholder="Cuéntanos sobre tu experiencia y objetivos de aprendizaje."/></label></div>{message&&<p className={styles.message}>{message}</p>}<button onClick={()=>void save()} disabled={saving}>{saving?<LoaderCircle/>:<Save/>}Guardar cambios</button></section></div></main>;
}
